[project]
name = "crssearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "datasette>=0.65.2",
    "sentence-transformers>=5.1.2",
    "sqlite-vec>=0.1.6",
    "streamlit>=1.52.1",
]
